services:
  # Single Full-Stack Web Service (Node + React SPA)
  - type: web
    name: powerhub
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: MONGO_URI
        value: mongodb+srv://powerhub:powerhub@powerhub.iietqg7.mongodb.net/?appName=powerhub
      - key: JWT_SECRET
        value: secret
      - key: FOOD_API_BASE
        value: https://world.openfoodfacts.org
