services:
  # Backend Web Service
  - type: web
    name: powerhub-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://powerhub:powerhub@powerhub.iietqg7.mongodb.net/?appName=powerhub
      - key: JWT_SECRET
        value: secret
      - key: FOOD_API_BASE
        value: https://world.openfoodfacts.org

  # Frontend Static Site
  - type: web
    name: powerhub-frontend
    env: static
    plan: free
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: PowerHub
          property: url

